[programs.localnet]
anchor_escrow = "3LLSGFJHcYJA4mawtw9zW3N1tfzSMPYHycJi984SEJ7T"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "https://rpc-mainnet-fork.epochs.studio"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
